# Generated by Django 3.2.4 on 2021-06-19 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_parroquia', models.CharField(choices=[('rural', 'Rural'), ('urbana', 'Urbana')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Parroquias',
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('viviendas', models.IntegerField(verbose_name='Número de viviendas')),
                ('parques', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Número de parques')),
                ('edificios', models.IntegerField(verbose_name='Número de edificios')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasparroquias', to='ordenamiento.parroquia')),
            ],
        ),
    ]
